### ISSUE TITLE
Line numbers are not outputted, correct symbols generated and in path

### ISSUE THREAD

**Issue by bolthar** [gimelfarb/ProductionStackTrace#1]
I've tried to use the Analyze.Library nuget package to extract line number infos from the exception report but couldn't - I get the instruction causing the exception but no line numbers.

Here's a sample of what I am doing - D:\symbols\ contains the latest symbols (which I copy-pasted from the debug/ folder)

```
catch (Exception ex)
            {
                var text = ExceptionReporting.GetExceptionReport(ex);
                var writer = new StringWriter();
                var pst = new ProductionStackTrace.Analyze.ExceptionReportInterpreter();
                pst.SymbolPaths.Add("D:\\symbols");
                pst.Translate(new StringReader(text), writer);
                MessageBox.Show(writer.GetStringBuilder().ToString());
            }
```

Here's the output:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at animationTest.TestObj..ctor(String test)
```

And here's the exception report:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at animationTest!0x06000009!animationTest.TestObj..ctor(String test) +0x9
==========
MODULE: animationTest => animationTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null; G:3b9e8688578a4f8e83f09c8f3f6a5d45; A:1
```

I'm most likely doing something stupid here :) but I've spent quite some time going through the examples and I really have no idea where to go next - sorry for disturbing you directly.

**Comment by mliesmons** [comment]
Same experience here with VS 2015, could it be we need update?
