### ISSUE TITLE
Not getting GUID and Age property of PDB in StackTrace

### ISSUE THREAD

**Issue by Steffaan** [gimelfarb/ProductionStackTrace#11]
Hi,

First of all I want to thank you for your great work on this project. I'm having some issues with the production not displaying the GUID and Age in the stacktrace.

When I deploy the application with debug configuration, everything is fine and I'm getting the GUID + age field. But when I deploy the application for release (obfuscated), I can't seem to get the fields into the stacktrace, it's displaying the MODULE: line but without the "G:{GUID} A:{AGE} fields.

What am I doing wrong here?

Thanks.

**Comment by icnocop** [comment]
This is probably a result of not building with "Debug Info".

In Visual Studio 2015:
Project Properties > Build > Advanced... > Debug Info > must not be `none`.
