### ISSUE TITLE
How do i find the line number?

### ISSUE THREAD

**Issue by DModder** [gimelfarb/ProductionStackTrace#5]
The linenumber isn't inside the ExceptionReporting.GetExceptionReport(ex)).
Where do i find it?

**Comment by gimelfarb** [comment]
Hi @DModder - line numbers would be shown when you run "Convert-ProductionStackTrace", which will use PDB information to extract line numbers. The GetExceptionReport(ex) is meant to be run in production, where you don't have PDBs installed.

Checkout the [README](https://github.com/gimelfarb/ProductionStackTrace) for info on how to examine the generated exception reports.
